spring:
  application:
    name: authentication

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: Adsfvabewryethadbgnq4ertjadfhjmetDHJarkmyshfzdjykmrtdsejkymhndgThJymhfngbfcsdd
  access-token-expiration: 7,200,000       # 2?? (ms)
  refresh-token-expiration: 604,800,000   # 7? (ms)
